### ISSUE TITLE
The toolbar icon is not shown properly

### ISSUE THREAD

**Issue by c0dev0id** [citizenos/ep_image_upload#12]
The upload icon does not show up properly in the toolbar. Tested in Chrome and Firefox on Windows.

![image](https://user-images.githubusercontent.com/44190565/82894258-9a1dcb80-9f52-11ea-8e16-9683ff32d11b.png)

**Comment by echristiaans** [comment]
I second this, have the same problem. Tested on MacOS with Firefox and Chrome.

**Comment by c0dev0id** [comment]
I've replaced it with 📤 in my installation. Maybe 📂 would be better? I looked througth the emojis that are available in most fonts. Or maybe 📷?

Ideal would be a picture in a frame as we know it from the other WYSIWYG editors.

EDIT: Ah, there it is: 🖼

**Comment by echristiaans** [comment]
Out of interest, how did you replace it? which file(s) did you change?

**Comment by tiblu** [comment]
@c0dev0id Thanks for the report!
What version of Etherpad are you using? 
We have not jet upgraded to latest (1.8.3) thus have not tested on it. 

Related issues:

* https://github.com/citizenos/citizenos-fe/issues/466

**Comment by c0dev0id** [comment]
@tiblu  I'm using the latest etherpad (master branch). 
However, the icon has nothing to do with the etherpad version.

@echristiaans Just replace the content here: https://github.com/citizenos/ep_image_upload/blob/master/templates/editBarButtons.ejs#L3

**Comment by echristiaans** [comment]
thanks, that worked for me.

**Comment by Vinc89** [comment]
Hello, I have the same issue. Could you please advise what exactly needs to be changed in the editBarButtons.ejs? Thanks

**Comment by echristiaans** [comment]
assuming you have installed Etherpad in `/opt/etherpad`, edit the file `/opt/etherpad/node_modules/ep_image_upload/templates/editBarButtons.ejs`.

```
<style>
  button.buttonicon.ep_image_upload.image_upload:before {
    content:"\E83A";
  }
</style>
```

What you need to change is the code `E83A` to something of your choosing. Keep in mind though, by default you can only choose what is defined in `src/static/font/config.json` - convert the `code` to hex, that's the number you need to configure. If you want another icon, you first need to add it to config.json.

**Comment by rasos** [comment]
`E83A` shows a nice picture icon, so this seems already perfect.

**Comment by woeterman94** [comment]
Same issue here. Should I make a pull request?

**Comment by tiblu** [comment]
> Same issue here. Should I make a pull request?

Sure, PR would be nice! I'm currently not actively developing EP, but @ilmartyrk MAY have time to review and help as needed.

**Comment by JohnMcLear** [comment]
This should be fine in develop.  I think the issue was due to a missing icon in EP fontawesome?

**Comment by JohnMcLear** [comment]
https://github.com/citizenos/ep_image_upload/pull/28
