### ISSUE TITLE
image export

### ISSUE THREAD

**Issue by ddeenniiss** [citizenos/ep_image_upload#13]
Is there a way to export the images in the documents?

**Comment by woeterman94** [comment]
Did you ever find an answer for your question?

**Comment by ilmartyrk** [comment]
@ddeenniiss @woeterman94 haven't tried any other export methods, but API-s export HTML has images included. If you have any suggestions or have checked other export methods any PR-s or updates are welcome

**Comment by woeterman94** [comment]
https://github.com/citizenos/ep_image_upload/pull/20

**Comment by JohnMcLear** [comment]
Solved.  Was due to a broken regexp
