### ISSUE TITLE
ep_ copy_ paste_ Images and ep_ image_ upload cannot coexist

### ISSUE THREAD

**Issue by Lynn-Bin** [citizenos/ep_image_upload#17]
When I installed ep_ copy_ paste_ images, use ep_ image_ upload failed to upload due to wrong upload image

Re step
1、installed ep_ image_ upload
2、installed ep_ copy_ paste_ images
3、use ep_ image_ upload failed to upload

**Comment by ilmartyrk** [comment]
that is because `ep_image_upload `is based from `ep_copy_paste_images`, it was made for our use case where `ep_copy_paste_images` didn't suit us too well
