### ISSUE TITLE
Does S3 bucket credentials are exposed while uploading ?

### ISSUE THREAD

**Issue by bharath-naik** [citizenos/ep_image_upload#23]
I have two questions related to the plug-in
 When the image is uploaded through the plug-in to s3
1. "addImage" in toolbar is not relfecting perfectly, it shows only at the top right corner of screen
2. Are the s3 credentials in settings.json are exposed in front while uploading

**Comment by JohnMcLear** [comment]
1. Already open as another issue.
2. No.
