### ISSUE TITLE
Line numbering is broken -- Testing in Azure

### ISSUE THREAD

**Issue by alexeisenhart** [citizenos/ep_image_upload#35]
Hello! I love this plugin, by the way.

I just got Etherpad set up and running in Azure. I mention this becausetThere were a number of issues that had to be addressed in Etherpad-Lite to support Azure, so the hosting environment might introduce some issues for the plugin as well.

Image uploading via copy/paste, drag/drop and the upload button seem to be working fine. But the line number spacing gets weird. 

In this image, I added a CSS rule via the Developer Tools console to resize the images to 25%. You can see that the line numbers resize reasonably.

![image](https://user-images.githubusercontent.com/72568950/109578815-db38a280-7ac5-11eb-9f24-749c1c88e3bb.png)

However, when I remove my CSS change, the spacing between the line numbers increases, but it seems to grow independent of the document context frame, and now I can't scroll down to view the rest of the document.

![image](https://user-images.githubusercontent.com/72568950/109579013-2c489680-7ac6-11eb-979f-963fdcac887e.png)

There are no client or server side errors.

If I disable line numbers then the extra space at the bottom goes away, but I can't scroll down to see the rest of the document.

![image](https://user-images.githubusercontent.com/72568950/109579238-834e6b80-7ac6-11eb-945b-923d3b723b13.png)

I *can* scroll with the cursor, but there are no scroll bars. I added a bunch of text at the top of the document (to push the images off screen) and this did not cause scrollbars to appear.

Please let me know if there's any additional information that I could provide!

**Comment by alexeisenhart** [comment]
I uninstalled the plugin and tried with just text, but I get the same error. This might be an Etherpad bug rather than this plugin.

The scrollbar scrolls the page down (to show more line numbers) rather than the document.

![image](https://user-images.githubusercontent.com/72568950/109579646-4afb5d00-7ac7-11eb-966b-02942b01d6e0.png)

**Comment by rhansen** [comment]
Possibly caused by a bug in this change: https://github.com/ether/etherpad-lite/pull/4831. Mind opening a new bug in the ether/etherpad-lite repo?

**Comment by JohnMcLear** [comment]
Yea I think this is a core issue, will look into it.

**Comment by JohnMcLear** [comment]
@seballot do you think you have time to look into this?  I can't checkout my branch to see if the code came from me or not because we closed it in favor of yours.

**Comment by rhansen** [comment]
Opened a bug in Etherpad core: https://github.com/ether/etherpad-lite/issues/4914

Feel free to close this one.

**Comment by alexeisenhart** [comment]
Closing this issue because it looks like a base Etherpad-lite changeset introduced the issue unintentionally.
