### ISSUE TITLE
Failed to load modules

### ISSUE THREAD

**Issue by kuba-orlik** [citizenos/ep_image_upload#36]
After enabling `ep_image_upload` in Etherpad 1.8.4, The image icon appears in the toolbar, but pressing it doesn't do anything. 

The JS console shows lots of errors like this (but for various different modules):

```
Failed to load 'ep_image_upload/static/js/toolbar' for 'ep_image_upload/ep_image_upload/client_hooks/postToolbarInit': Error: The module at "ep_image_upload/static/js/toolbar" does not exist. ace2_common.js:36:445
```

**Comment by JohnMcLear** [comment]
I don't know if it will work in 1.8.4....  You might want to update :)

**Comment by kuba-orlik** [comment]
Oh, I didn't know I'm so many version behind. Will update. Closing for now. Thanks for a quick response!
