### ISSUE TITLE
Image cropping

### ISSUE THREAD

**Issue by Hiswe** [citizenos/ep_image_upload#4]
Hi,

thanks for ep_image_upload! it's working amazingly fine.

I would like to know what is the best solution to implement an image cropping into the fileupload.
I consider using [Croppie](http://foliotek.github.io/Croppie/)

To be honest I have not a deep understanding of how the Etherpad editor works.
By looking at your code, I don't see any custom dom events/hooks where I can put in a way my custom code (with a custom etherpad plugin) or even if it's a good practice to extend a plugin by another plugin.

So I though I can come with a PR where:
- an option will be present in the `ep_image_upload` config (so we can support some options of the Croppie)
- add Croppie as a dependency in the `package.jon`
- base on the config, switch from your upload code to a croppie one
- on the upload show a modal to display the croppie UI
- then do the upload

What are your insights on this?

Thanks in advance

**Comment by ilmartyrk** [comment]
Hi, thank you for your kind words. I am not sure how good it is to extend a plugin by another, but your PR list looks pretty good and solid. Most code you can probably add to `/static/js/clientHooks.js` under `postToolbarInit` where the upload handling is currently done. For settings, you could probably add all configure options as a sub-item in config `ep_image_upload.croppie` this way it will be more flexible to users. All in all, this is a really good idea from you and if you have any more questions I'll try to answer you as quickly as I can.

**Comment by Hiswe** [comment]
@ilmartyrk thanks for your answer!

I will close this issue for now and hope I can come up with a PR in the future.

Thanks again
