### ISSUE TITLE
Under which licence is ep_image_upload published?

### ISSUE THREAD

**Issue by aleray** [citizenos/ep_image_upload#6]
Hello,

could you specify under which licence is `ep_image_upload` published? I'm interested to adapt it (and contribute back) but  I don't know which rights are attached to the project.

Thanks!

**Comment by hyandell** [comment]
Agreed.  Is it Apache-2.0 like https://github.com/JohnMcLear/ep_copy_paste_images ?

**Comment by ilmartyrk** [comment]
Yes it is Apache 2.0 will soon add the file to the project too

**Comment by JohnMcLear** [comment]
Apache 2 is now included in project..
